chore: add scripts to map AGG token
axieinfinity/ronin-bridge-contracts pull request #3
Opened 2023-12-19 06:26 UTC by minh-bq

### Description
This PR adds 2 scripts for creating 2 proposals on Ronin and Ethereum for mapping AGG token to bridge

2023-12-19 06:26 UTC, minh-bq commented on script/20231218-maptoken/20231218-maptoken-mainchain.s.sol
> +  uint256 constant _dailyWithdrawalLimit = 0;
TBD

2023-12-21 03:40 UTC, ducthotran2010 requested changes

2023-12-21 03:40 UTC, ducthotran2010 commented on script/20231218-maptoken/20231218-maptoken-mainchain.s.sol
> +    _verifyProposalGasAmount(_roninBridgeManager, targets, values, calldatas, gasAmounts);
We should verify it on the companion network

2023-12-21 07:15 UTC, ducthotran2010 approved these changes

2023-12-21 07:17 UTC, TuDo1403 approved these changes

2023-12-21 07:17 UTC, merged